[project]
name = "weatherapi-ingestion-pipeline"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Caio Aloisio", email = "caio.aloisio@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openmeteo-requests>=1.7.5",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "pyodbc>=5.3.0",
    "python-dotenv>=1.2.2",
    "requests-cache>=1.3.3",
    "retry-requests>=2.0.0",
    "sqlalchemy>=2.0.51",
    "supabase>=2.31.0",
]

